/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module halfadder(a, b, sum, c_out);
  input a;
  wire a;
  input b;
  wire b;
  output c_out;
  wire c_out;
  output sum;
  wire sum;
  XOR2x2_ASAP7_75t_R _0_ (
    .A(a),
    .B(b),
    .Y(sum)
  );
  NAND2xp33_ASAP7_75t_R _1_ (
    .A(a),
    .B(b),
    .Y(c_out)
  );
endmodule
